% Workshop 10: Triple integrals: do me a solid
% Math 275 Calculus 3
% November 4, 2013

# Workshop 10: Triple integrals: do me a solid

This workshop gives you a chance to practice setting up triple integrals.

## Integrals: do me a solid

\begin{questions}

\question Let $E$ be the region under the plane $2x+3y+z=6$ that lies in the first octant. Draw the region. In this case, I suggest drawing the plane by first drawing the points where it intersects the coordinate axes, and then drawing the triangle these points determine.
Evaluate the integral
\begin{equation*}
\iiint_{E} x \; dV
\end{equation*}
in the order $dz \; dy \; dx$, verifying that the result is 9/2. In your figure, make sure to draw a typical slice containing a typical segment.

\dwrspace{1}

\newpage

\question Describe the regions expressed by the iterated integrals.

\begin{parts}

    \part $\displaystyle \int_{-2}^{4} \int_{2}^{6} \int_{0}^{5} f(x,y,z) \; dy \; dx \; dz$

    \dwrspace{1}

    \part $\displaystyle \int_{0}^{3} \int_{0}^{3} \int_{0}^{3-y} f(x,y,z) \; dz \; dy \; dx$

    \dwrspace{1}

    \part $\displaystyle \int_{0}^{2} \int_{0}^{3} \int_{4x/3}^{4} f(x,y,z) \; dz \; dx \; dy$

    \dwrspace{1}

    \part $\displaystyle \int_{-3}^{3} \int_{-\sqrt{9-x^2}}^{\sqrt{9-x^2}} \int_{-\sqrt{9-x^2-y^2}}^{\sqrt{9-x^2-y^2}} f(x,y,z) \; dz \; dy \; dx$

    \dwrspace{1}

    \part $\displaystyle \int_{-3}^{3} \int_{-\sqrt{9-x^2}}^{\sqrt{9-x^2}} \int_{-3}^{3} f(x,y,z) \; dz \; dy \; dx$

    \dwrspace{1}

\end{parts}

\end{questions}

