% Higher derivatives and modeling
% Math 275 Multivariable Calculus
% October 9, 2013

# Higher derivatives and modeling

## Recap: slices, partial derivatives, and tangent lines

We saw previously that if $f(x,y)$ is a function of two variables, each of its partial derivatives $f_x(x,y)$ and $f_y(x,y)$ gives the slopes of tangent lines to slice curves.

If $(a, b)$ is a point in the plane, the slice curves through $(a,b)$ are the graphs of $z = f(a, y)$ (in the plane $x = a$) and $z = f(x, b)$ (in the plane $y = b$).

## Partial derivatives

If the slice functions $f(a, y)$ and $f(x,b)$ are differentiable (in the one-variable sense), their derivatives are $f_y(a,y)$ and $f_x(x,b)$. These functions are ordinary derivatives, so they compute tangent slopes in the usual way.

- The tangent line equations: 
- $z = f(a, b) + f_x(a,b)(x - a)$
- $z = f(a, b) + f_y(a,b)(y - b)$

This is the old tangent line approximation formula, just twice in different directions.

## Higher derivatives

The pure partials $f_{xx}$ and $f_{yy}$ are easy to understand in terms of the slices. They tell us about concavity, just like ordinary second derivatives. Namely,

> - $f_{xx}(x,b)$ is positive (negative) if $f(x,b)$ is concave up (concave down)
> - $f_{yy}(a,y)$ is positive (negative) if $f(a,y)$ is concave up (concave down)

## The mixed partial

Recall that a smooth function has just one mixed partial, because $f_{xy} = f_{yx}$ by Clairaut's theorem.

This partial is harder to visualize in terms of graphs. The activity ([Workshop 07][w07]) should illuminate its meaning.

## Curve shapes via derivatives

Recall how graph-sketching works in ordinary calculus: one identifies the locations where the first derivative changes sign (these are the local maxima and minima) and where the second derivative changes sign (these are the points of inflection). There are four possible "curve shapes":

1. Increasing, concave up
2. Increasing, concave down
3. Decreasing, concave up
4. Decreasing, concave down

Once you know which shape occurs on which interval, just paste them together.

## Universality of quadratic curves

Smooth functions are very well approximated *locally* by their quadratic approximations (second-order Taylor series). We'll use ideas about quadric surfaces (corresponding to degree 2 polynomials in 2 variables) to do some modeling of more interesting multidimensional phenomena.

[w07]: ../../workshops/07/Workshop.pdf