% Tangent planes and differentials
% Math 251 Calculus 3
% October 1, 2013

# Tangent planes and differentials

## Recap: slices, partial derivatives, and tangent lines

We saw previously that if $f(x,y)$ is a function of two variables, each of its partial derivatives $f_x(x,y)$ and $f_y(x,y)$ gives the slopes of tangent lines to slice curves.

If $(a, b)$ is a point in the plane, the slice curves through $(a,b)$ are the graphs of $z = f(a, y)$ (in the plane $x = a$) and $z = f(x, b)$ (in the plane $y = b$).

## Partial derivatives

If the slice functions $f(a, y)$ and $f(x,b)$ are differentiable (in the one-variable sense), their derivatives are $f_y(a,y)$ and $f_x(x,b)$. These functions are ordinary derivatives, so they compute tangent slopes in the usual way.

- The tangent line equations: 
- $z = f(a, b) + f_x(a,b)(x - a)$
- $z = f(a, b) + f_y(a,b)(y - b)$

This is the old tangent line approximation formula, just twice in different directions.

## A candidate for the tangent plane

The tangent lines in the $(x,y)$-direction determine a unique plane. Its equation is
$$ z = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y - b). $$

Rearranging this a bit, we can confirm it's a plane:
$$ \angl{f_x(a,b), f_y(a,b), 1} \cdot \angl{x - a, y - b, z - f(a,b)}. $$

By 12.5, this is the equation of a plane passing through the point $(a, b, f(a, b))$ normal to the vector $\angl{f_x(a,b), f_y(a,b), 1}$.

We call the RHS $L(x,y)$ the *linearization* of $f$ at the point $(a,b)$.

## Local linearity

Having a tangent plane means the graph of the surface is *locally linear*. If we zoom way in, the surface looks flat. The algebraic criterion for this turns out to be
$$ \lim_{(x, y) \to (a, b)} \frac{f(x, y) - L(x,y)}{\norm{\angl{x,y} - \angl{a,b}}} = 0$$
and so we adopt this as the definition of *differentiability*.

## Three ways to say it

All of the following are equivalent:

- $f(x,y)$ is differentiable at $(a,b)$
- $f(x,y)$ is locally linear at $(a,b)$
- the graph of $L(x,y)$ is tangent to the graph of $f$ at $(a,b)$

## Criteria for differentiability

If *any* plane is tangent to the graph of $f$ at $(a,b)$, it must be the graph of $L(x,y) = f(a,b) + f_x(a,b)(x-a) + f_y(a,b)(y - b)$. That's the only plane that contains the tangent lines.

How do we know the tangent plane exists?

> If $f_x$ and $f_y$ exist and are continuous at $(a,b)$, then the three equivalent conditions given above are all true.

## Differentials and the linearization

If $(x,y)$ is near $(a,b)$ (in other words, if the magnitude $\norm{\angl{x,y} - \angl{a,b}}$ is small), then $L(x,y) \approx f(x,y)$. Let us write $\Delta x = x - a$, $\Delta y = y - b$, and $\Delta f = f(x,y) - f(a,b)$. 

Then $\Delta f \approx f_x(a,b)\Delta x + f_y(a,b) \Delta y$.

 